#!/usr/bin/env python
# encoding: utf-8

themes = """
	default
""".split()

def configure(conf):
	conf.check_tool('edje', tooldir='waf_tools')

def build(bld):
	for theme in themes:
		bld.new_task_gen(
			features     = 'edje',
			source       = theme + '/' + theme + '.edc',
			target       = theme + '.edj',
			cwd          = bld.path.abspath() + '/' + theme,
			install_path = None
		)
