#!/usr/bin/env python
# encoding: utf-8

sources = """
	rockon.c
	lcfg_static.c
	rockon_data.c
	rockon_config.c
	xmms_conn.c
	commands.c
	broadcasts.c
	media_info.c
	playlist.c
	collection.c
	ui_update.c
	gui.c
	callbacks.c

	util.c
"""

libs = """
	ecore
	ecore-file
	eina-0
	elementary
	xmms2-client
	xmms2-client-ecore
"""

def configure(conf):
	conf.env.append_value('CCFLAGS', '-Wall')
	conf.env.append_value('CCFLAGS', '-O0')
	conf.env.append_value('CCFLAGS', '-g')
	conf.env.append_value('CCFLAGS', '-DDEBUG')

	conf.check_tool('gcc')
	conf.check_tool('edje', tooldir='waf_tools')

	for lib in libs.split():
		conf.check_cfg(package=lib, args='--cflags --libs')

def build(bld):
	bld.new_task_gen(
		features     = 'cc cprogram',
		source       = sources.split(),
		target       = 'rockon',
		includes     = '.',
		install_path = None,
		uselib       = libs.upper().split()
	)
