#!/usr/bin/env python
# encoding: utf-8

sources = """
	rockon.c
	error.c
	lcfg_static.c
	config.c
	status.c
	xmms_conn.c
	commands.c
	edje_bridge.c
	elm_bridge.c
""".split()

libs = """
	ecore-evas
	elementary
	xmms2-client
	xmms2-client-ecore
"""

def configure(conf):
	conf.env.append_value('CCFLAGS', '-Wall')
	conf.env.append_value('CCFLAGS', '-O0')
	conf.env.append_value('CCFLAGS', '-g')

	conf.check_tool('gcc')

	for lib in libs.split():
		conf.check_cfg(package=lib, args='--cflags --libs')

def build(bld):
	bld.new_task_gen(
		features     = 'cc cprogram',
		source       = sources,
		target       = 'rockon',
		includes     = '.',
		install_path = None,
		uselib       = libs.upper().split()
	)

